@Backend_HostAddress = http://localhost:5148

### Get all customers
GET {{Backend_HostAddress}}/api/customer
Accept: application/json

### Create a new customer
POST {{Backend_HostAddress}}/api/customer
Content-Type: application/json

{
  "name": "John Doe",
  "isActive": true
}

###
