@Backend_HostAddress = http://localhost:5148

### Get all customers
GET {{Backend_HostAddress}}/api/customer
Accept: application/json

### Create a new customer
POST {{Backend_HostAddress}}/api/customer
Content-Type: application/json

{
  "name": "John Doe",
  "isActive": true
}

### register new user
POST {{Backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "babe",
  "password": "babe123",
  "email": "babe@example.com"
}

### validate user credentials
POST {{Backend_HostAddress}}/api/auth/validate
Content-Type: application/json

{
  "username": "babe",
  "password": "babe123"
}

### create role
POST {{Backend_HostAddress}}/api/role/create
Content-Type: application/json
{
  "RoleType": "User"
}
