@ServiceA_HostAddress = http://localhost:5234

# Customer API (proxying to Backend)

# Update a customer
PUT {{ServiceA_HostAddress}}/api/customer/561a4aa6-342d-4523-b64f-966c927b9b16?active=false
Content-Type: application/json
Authorization: <token>
### Register new user
POST {{ServiceA_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "Test@1234",
  "email": "test@example.com"
}

### Login
POST {{ServiceA_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "Test@1234"
}

### publish order
POST {{ServiceA_HostAddress}}/api/order/publish
Content-Type: application/json
Authorization: <token>
{
    "Id":  "test1",
    "CustomerName":  "Alice",
    "Items": [
        {
            "Name":  "Item1",
            "Quantity":  1
        }
    ]
}

### get all orders
GET {{ServiceA_HostAddress}}/api/order
Content-Type: application/json
Authorization: <token>
