@ServiceA_HostAddress = http://localhost:5234

# Customer API (proxying to Backend)

# Update a customer
PUT {{ServiceA_HostAddress}}/api/customer/561a4aa6-342d-4523-b64f-966c927b9b16?active=false
Content-Type: application/json


###
